version: "3"
services:
  monapp:
    image: monimage
    depends_on:
      - redis
    ports:
      - "80:80"
    networks:
      - monreseau
    environment:
      - NOM=les amis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - monreseau

networks:
  monreseau:
